sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
script:
  - yarn start validate
  - yarn start validate.examples
after_success:
  - yarn start report-coverage
  - yarn start release
branches:
  only:
    - master
